## Timestamp for output directory
timestamp: "20250902"

## Configuration for downloading genomes
genus: "Streptomyces"
assemblylevel: "complete" # Options: {complete,chromosome,contig,scaffold,all}
overwrite: "True" # Options: {True,False}
download_genomes_db: "refseq" # Options: {refseq,genbank,both}
repository: "bacteria" # Options: {bacteria,fungi,invertebrate,metagenomes,other,plant,protozoa,vertebrate_mammalian,vertebrate_other,viral}
max_genomes: "5"
#required_genomes: "GCF_005519465.1 GCF_001685355.1" # space-separated list of genome accessions that must be included in the download

## Configuration for InterproScan
ipr_appl: "Pfam,PROSITEPROFILES,CDD" #(in addition to the default InterproScan)
#ipr_cpu: 4 # Number of CPUs to use for InterproScan

## Configuration for proteinortho
proteinortho_project: "streptomyces"
proteinortho_cpu: 8
cog_directory: "cog"
minimum_cog_size: 4 # min number of proteins to be considered to create the COG fasta files

## TF families of interest (just an example for now)
tf_families: "LacI,GntR" # options: {AraC, ArgR, ArsR, AsnC, BirA, Crp, DeoR, Fis, Fur, GntR, IclR, LacI, LexA, LuxR, LysR, MarR, PadR, PhoB, SinR, TetR, TrmB}
tf_perc_threshold: 70 # Percentage of proteins in the COG, for the COG to be considered in following analyses

## Upstream region extraction
upstream_region_length: [100, 300, 500] # Length of the upstream region to extract
upstream_stop_cds: True # Options: {True,False} - If True, stop codons will be included in the upstream region

## MEME parameters
meme_modes: ["anr", "zoops"]
meme_lengths: [30, 20, 10]

## Integrate dbCAN and TF data
tf_dbcan_method: "neighbouring" # Options: {neighbouring,overlap,both} - Method to integrate dbCAN and TF data
tf_dbcan_extension: "0" # Extension length for the CGC location in base pairs, to get neighbouring TFs
tf_dbcan_neighbours: "2" # Number of CGC neighbouring genes, to get neighbouring TFs

## Target Transcription Factor ??? gene id or something, uniprot number -- is it included?
## include an option: genome to absolutely include, and/or list of genomes you want to have in the analysis. 
## option to input a list of genomes to download (GCF numbers OR exact Species names) 
## Is uniprot id in the genome annotation? 
## Target TF: then you can at the end filter the results to just analyse this TF? 
## Option: delete additional data that is not needed (to save space). 
## Option: delete OrthoGroups that are not target TF families? 
## antismash: predict regulons on them. Integrate Combatt? 
## Test LacI007 -- as a target TF family. 
## Integrate COGs to the dbCAN-TF integration??? is it possible? 